config/routes.rb
Connoisseur::Application.routes.draw do
  resources :drinks
  get 'drinks_stouts' => "drinks#stouts"
  get 'drinks_pilsner' => "drinks#pilsner"
  get 'drinks_porter' => "drinks#porter"
  get 'drinks_ipa' => "drinks#ipa"
  root to: 'drinks#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drinks_controller.rb
require 'open-uri'

class DrinksController < ApplicationController
  def index
    @time = Time.now
    @t = (@time.hour)
    page = params[:page] || 1

    drinks_json = open("http://lcboapi.com/products?page=#{page}").read
    @drinks = JSON.parse(drinks_json)

    stouts_json = open("http://lcboapi.com/products?q=stout").read
    @stouts = JSON.parse(stouts_json)

    porter_json = open("http://lcboapi.com/products?q=porter").read
    @porters = JSON.parse(porter_json)
  end

  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def show
    id = params[:id]
    product_json = open("http://lcboapi.com/products/#{id}").read
    @product = JSON.parse(product_json)
  end

  def stouts
    stouts_json = open("http://lcboapi.com/products?q=stout").read
    @stouts = JSON.parse(stouts_json)
  end

  def pilsner
    pilsner_json = open("http://lcboapi.com/products?q=pilsner").read
    @pilsner = JSON.parse(pilsner_json)
  end

  def porter
    porter_json = open("http://lcboapi.com/products?q=porter").read
    @porter = JSON.parse(porter_json)
  end

  def ipa
    ipa_json = open("http://lcboapi.com/products?q=ipa").read
    @ipa = JSON.parse(ipa_json)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/views/drinks/create.html.erb
<h1>Drinks#create</h1>
<p>Find me in app/views/drinks/create.html.erb</p>

app/views/drinks/destroy.html.erb
<h1>Drinks#destroy</h1>
<p>Find me in app/views/drinks/destroy.html.erb</p>

app/views/drinks/edit.html.erb
<h1>Drinks#edit</h1>
<p>Find me in app/views/drinks/edit.html.erb</p>

app/views/drinks/index.html.erb
<div class="parent">
		<div>
			<center>
				<h1 class="weather">It's <%= @t %>:<%= @time.min %>, what mood are you in?</h1>
			</center>
		</div>
	<%= link_to drinks_pilsner_path(:id => "pilsner") do%>
		<div class="pilsner">
			<h1 class="titles">Pilsner</h1>
		</div>
	<% end %>
	<%= link_to drinks_stouts_path(:id =>"stout") do%>
		<div class="stout">
			<h1 class="titles">Stout</h1>
		</div>
	<% end %>
	<%= link_to drinks_ipa_path(:id => "ipa") do%>
		<div class="ipa">
			<h1 class="titles">IPA</h1>
		</div>
	<% end %>
	<%= link_to drinks_porter_path(:id => "porter") do%>
		<div class="porter">
			<h1 class="titles">Porter</h1>
		</div>
	<% end %>


</div>

app/views/drinks/ipa.html.erb
<div id="ipa">
<div class="wrapper">
<% @ipa['result'].each do |product| %>
		  <section class="beers">
		    <%= link_to product['name'], drink_path(product['id']) %>
		  </section>
		<% end %>
		</div>
</div>

app/views/drinks/new.html.erb
<h1>Drinks#new</h1>
<p>Find me in app/views/drinks/new.html.erb</p>

app/views/drinks/pilsner.html.erb
<div id="pilsner">
<div class="wrapper">
<% @pilsner['result'].each do |product| %>
		  <section class = 'beers'>
		    <%= link_to product['name'], drink_path(product['id']) %>
		  </section>
		<% end %>
		</div>
</div>

app/views/drinks/porter.html.erb
<div id = "porter">
<div class="wrapper">
<% @porter['result'].each do |product| %>
		  <section class="beers">
		    <%= link_to product['name'], drink_path(product['id']) %>
		  </section>
		<% end %>
		</div>
</div>

app/views/drinks/show.html.erb
<%= @product['result']['name'] %>
<%= image_tag(@product['result']['image_thumb_url']) %>

app/views/drinks/stouts.html.erb
<div id="stout">
<div class="wrapper">
<% @stouts['result'].each do |product| %>
		  <section class="beers">
		    <%= link_to product['name'], drink_path(product['id']) %>
		  </section>
		<% end %>
		</div>
</div>

app/views/drinks/update.html.erb
<h1>Drinks#update</h1>
<p>Find me in app/views/drinks/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Connoisseur</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>